# Generated by Django 5.2.3 on 2025-06-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('repuesto', 'Repuesto'), ('accesorio', 'Accesorio'), ('usado', 'Producto Usado')], default='producto', max_length=20),
        ),
    ]
