# Generated by Django 5.2.2 on 2025-06-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_permitir_sin_stock_producto_tipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
    ]
