# Generated by Django 5.2.2 on 2025-06-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
