# Generated by Django 5.2.2 on 2025-06-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tecnico', 'Servicio Técnico'), ('instalacion', 'Instalación de Cámaras')], max_length=20)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('accesorios', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnosticado', 'Diagnosticado'), ('presupuestado', 'Presupuestado'), ('en_reparacion', 'En reparación'), ('listo', 'Listo para entregar'), ('cotizado', 'Cotizado'), ('pendiente_instalacion', 'Pendiente de instalación'), ('instalado', 'Instalado'), ('entregado', 'Entregado')], default='recibido', max_length=30)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ruta_comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('ruta_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
