# Generated by Django 5.2.3 on 2025-06-19 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_remove_cliente_observaciones'),
        ('inventario', '0002_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tecnico', 'Servicio Técnico'), ('instalacion', 'Instalación de Cámaras')], max_length=20)),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('accesorios', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('diagnosticado', 'Diagnosticado'), ('presupuestado', 'Presupuestado'), ('en_reparacion', 'En reparación'), ('listo_para_entregar', 'Listo para entregar'), ('entregado', 'Entregado'), ('cotizado', 'Cotizado'), ('pendiente_instalacion', 'Pendiente instalación'), ('instalado', 'Instalado')], default='recibido', max_length=30)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ruta_comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('ruta_factura', models.FileField(blank=True, null=True, upload_to='facturas_pdfs/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'repuesto'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='servicios.servicio')),
            ],
        ),
    ]
