# Generated by Django 5.2.2 on 2025-06-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('diagnosticado', 'Diagnosticado'), ('presupuestado', 'Presupuestado'), ('en_reparacion', 'En reparación'), ('listo_para_entregar', 'Listo para entregar'), ('entregado', 'Entregado'), ('cotizado', 'Cotizado'), ('pendiente_instalacion', 'Pendiente instalación'), ('instalado', 'Instalado')], default='recibido', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='ruta_factura',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdfs/'),
        ),
    ]
