# Generated by Django 5.2.3 on 2025-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
