# Generated by Django 5.2.2 on 2025-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_codigo_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
