# Generated by Django 5.2.2 on 2025-06-12 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_permitir_sin_stock_producto_tipo_and_more'),
        ('servicios', '0003_alter_servicio_costo_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(limit_choices_to={'tipo': 'repuesto'}, on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_usados', to='servicios.servicio')),
            ],
        ),
    ]
