# Generated by Django 5.2.2 on 2025-06-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_repuestousado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='usa_repuestos',
            field=models.BooleanField(default=False, help_text='Marcar si este trabajo utiliza repuestos.'),
        ),
    ]
