# Generated by Django 5.2.2 on 2025-06-12 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_servicio_usa_repuestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='usa_repuestos',
        ),
    ]
