# Generated by Django 5.2.2 on 2025-06-11 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
        ('servicios', '0003_alter_servicio_costo_total'),
        ('ventas', '0006_alter_venta_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='servicio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
    ]
