# Generated by Django 5.2.2 on 2025-06-10 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_cedula_alter_cliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')], verbose_name='Cédula'),
        ),
    ]
