# Generated by Django 5.2.3 on 2025-06-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='observaciones',
        ),
    ]
